"""Initial schema

Revision ID: aeedfa3b6aaa
Revises: 
Create Date: 2026-06-07 18:28:30.393104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeedfa3b6aaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('ema20', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ema200', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rsi14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('atr14', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indicators'))
    )
    op.create_index('idx_indicators_symbol_time', 'indicators', ['symbol', 'timestamp'], unique=False)
    op.create_table('ohlc_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=True),
    sa.Column('candle_timestamp', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ohlc_data'))
    )
    op.create_index('idx_ohlc_symbol_time', 'ohlc_data', ['symbol', 'candle_timestamp'], unique=False)
    op.create_index('idx_ohlc_time', 'ohlc_data', ['candle_timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('order_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('idx_orders_broker_id', 'orders', ['broker_order_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['order_status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('fno_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks'))
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('entry_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('exit_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('idx_trades_entry_time', 'trades', ['entry_time'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy_name'], unique=False)
    op.create_index('idx_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('instrument_token', sa.BigInteger(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('strike', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name=op.f('fk_instruments_stock_id_stocks'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    op.create_index(op.f('ix_instruments_instrument_token'), 'instruments', ['instrument_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instruments_instrument_token'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_entry_time', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_table('signals')
    op.drop_table('positions')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_broker_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_ohlc_time', table_name='ohlc_data')
    op.drop_index('idx_ohlc_symbol_time', table_name='ohlc_data')
    op.drop_table('ohlc_data')
    op.drop_index('idx_indicators_symbol_time', table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
